apiVersion: v2
name: kubeflow
version: "1.6.2"
kubeVersion: ">=1.20.0"
description: |
  Machine learning (ML) workflows on Kubernetes made simple.
type: application
keywords:
  - "Kubeflow"
  - "Kubernetes"
  - "machine learning"
  - "tensorflow"
  - "pytorch"
  - "XGBoost"
home: https://github.com/BodhiHu/kubeflow-ops
sources:
  - https://github.com/BodhiHu/kubeflow-ops
  - https://github.com/kubeflow/manifests
dependencies:
  - name: cert-manager
    version: "1.5.0"
    alias: cert-manager
    condition: cert-manager.enabled
  - name: dex
    version: "2.31.2"
    condition: dex.enabled
  - name: istio
    version: "1.14.1"
    condition: istio.enabled
  - name: knative-serving
    version: "1.2.5"
  - name: minio
    version: "1.0"
    condition: minio.enabled
appVersion: "1.6.1"
